### ISSUE TITLE
Need to know how far the SD card sticks out

### ISSUE THREAD

**Issue by Joedang** [psas/lv3.0-camera-ring#1]
I set up the camera housing to have a clipped washer that hangs over the SD card to prevent it from jiggling out (see below). You just rotate the washer out of the way when you want to remove the SD card.  After inserting the card, rotate the washer over it and tighten the screw. This way, we can be sure they're secure and also be able to remove them easily. 

**I need to know if (and by how much) the SD card will stick out of its socket when inserted**, so I can size this feature so it doesn't press on the SD card.

![image](https://user-images.githubusercontent.com/16861664/36477043-af144c36-16b4-11e8-800f-a540eaf7e710.png)
![image](https://user-images.githubusercontent.com/16861664/36477054-bd301a34-16b4-11e8-962d-2f8420eb910a.png)

**Comment by andrewgreenberg** [comment]
This feature isn't necessary. The RunCam Split 2 uses a metal shield to hold in the SD card. it clips over the card, and the edge of the board too from what I can tell, and holds the SD card in. You pry up the little "finger" that goes over the card, and that's how you take out and insert the SD card.

So I think the washer + bolt is unnecessary.

**Comment by Joedang** [comment]
I'm not sure how much we should trust that retainer. It seems like something that would vibrate around during flight. (Though, the washer has the same problem.)

**Comment by Joedang** [comment]
Dumping the washer idea, since tape is a thing that exists.
